title: Fixing the position of a background image
hero_image: images/banner.png
description: Fixing the position of a background image
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Fixing the position of a background image